"use strict";
const { renderStandardPage } = require("../../components/pageBuilder");

module.exports = {
  slug: "/gift-code/",
  title: "55 Club Gift Code — Redeem Your Code",
  metaDescription:
    "Redeem a 55 Club gift code and credit bonus balance to your account. Codes are shared via social channels, events and support, and are usually time-limited.",
  build() {
    return renderStandardPage({
      slug: "/gift-code/",
      breadcrumb: [{ label: "Home", href: "/" }, { label: "Gift Code" }],
      hero: {
        eyebrow: "Redemption",
        h1: "55 Club Gift Code",
        lead: "Enter a gift code here to credit bonus balance to your account. Codes are shared through our social channels, live events and support team — most are time-limited and can only be redeemed once per account.",
        primary: { label: "Register", href: "/register/" },
        secondary: { label: "See Invite Code", href: "/invite-code/" },
      },
      intro: [
        "Gift codes are short promo codes that credit bonus balance directly to your account when you enter them here. We release them through our social channels, during live events and giveaways, and sometimes through Customer Support as a goodwill credit — keep an eye on those channels if you want to catch them as they're released.",
        "Redeeming one takes seconds: type or paste the code into the field on this page, hit submit, and the bonus lands in your balance immediately if the code is valid. There's no multi-step process — one field, one action, one result.",
        "Most codes are time-limited, so a code that worked last week may no longer be valid, and most are single-use per account, so a code already redeemed on your account won't work a second time even if you find it circulating again elsewhere.",
        "Gift Code sits alongside Invite Code as a related but different mechanic — gift codes are issued by 55 Club itself, while invite codes are generated by you for referring friends. If you're looking to share a code rather than redeem one, that's Invite Code.",
      ],
      features: {
        eyebrow: "Gift Code Page Features",
        title: "How Redemption Works",
        text: "Four things to know before you enter a code.",
        cols: 4,
        items: [
          { icon: "ticket", title: "Single-Field Redemption", text: "Enter your code and submit — bonus balance credits instantly if it's valid." },
          { icon: "check", title: "Format Guidance", text: "The field shows expected code length and character format before you submit." },
          { icon: "shield", title: "Clear Error Messages", text: "Distinct messages for invalid, already-used and expired codes." },
          { icon: "gift", title: "Regularly Released", text: "New codes go out through social channels, events and support." },
        ],
      },
      infoSections: [
        {
          eyebrow: "Redemption Flow",
          title: "One Field, Instant Result",
          paragraphs: [
            "Type your code into the field on this page and submit — you'll see a result immediately, without leaving the page or waiting on a page reload. If the code is valid, the bonus credits to your balance right away and you'll see a confirmation.",
            "Because this is a single-screen action, there's nothing else to fill out — just the code itself. Codes are typically a mix of letters and numbers of a fixed length, and the field will flag an obviously malformed entry before you even submit it.",
          ],
          sideList: {
            title: "What Each Error Means",
            items: [
              "Invalid format — the code doesn't match the expected pattern",
              "Already used — this code was already redeemed on your account",
              "Expired — the code's active window has passed",
              "Not found — no matching code exists in our system",
            ],
          },
        },
        {
          eyebrow: "Gift Code vs. Invite Code",
          title: "Two Related but Different Mechanics",
          reverse: true,
          paragraphs: [
            "Gift codes come from us — released through promotions, live events or Customer Support. Invite codes come from you — a personal code you generate and share with friends to earn a referral bonus. They look similar and are easy to mix up, but they work in opposite directions: one you receive and redeem, the other you generate and share.",
            "If you were expecting to find your own referral code on this page, head to Invite Code instead — this page is specifically for entering codes you've received, not generating your own.",
          ],
          asideTitle: "Where to Find New Codes",
          asideText: "We post gift codes on our social channels and during live events, and Customer Support sometimes issues one directly. Follow our channels to catch new codes as soon as they drop.",
        },
      ],
      extraSection: {
        eyebrow: "Good to Know",
        title: "Timing and Account Limits",
        paragraphs: [
          "Because codes are time-limited, it's worth redeeming one as soon as you get it rather than saving it for later — a code valid today isn't guaranteed to still work next week. If a code you're trying returns an expired message, that's the most likely reason.",
          "Codes are also generally limited to one redemption per account, so sharing a code you've already used with a friend won't let them redeem it a second time on your account, and using someone else's already-redeemed code won't work on yours either.",
          "If you believe you have a valid, unused code that isn't going through, Customer Support can check the code's status on your account and help sort out what's happening.",
        ],
      },
      relatedLinks: {
        title: "Related Pages",
        links: [
          { label: "Invite Code", href: "/invite-code/" },
          { label: "Promotions", href: "/promotions/" },
          { label: "Bonus", href: "/bonus/" },
          { label: "Rewards", href: "/rewards/" },
          { label: "Customer Support", href: "/customer-support/" },
        ],
      },
      faq: {
        items: [
          { q: "How do I redeem a gift code?", a: "Enter it into the field on this page and submit. If it's valid, bonus balance is credited to your account immediately." },
          { q: "What if my code doesn't work?", a: "You'll see one of four specific messages — invalid format, already used, expired, or not found — so you know exactly what happened." },
          { q: "Where do gift codes come from?", a: "We release them through our social channels, live events and giveaways, and occasionally through Customer Support." },
          { q: "How is Gift Code different from Invite Code?", a: "Gift codes are issued by 55 Club and redeemed here; invite codes are generated by you and shared with friends for referral bonuses." },
          { q: "Can I use the same code twice?", a: "No — codes are limited to one redemption per account, so a code already used on your account won't work again." },
          { q: "How long do gift codes stay valid?", a: "Most are time-limited, so redeem a code as soon as you receive it. An expired code will show a clear expired message if you try it late." },
          { q: "Can someone else use a code I've already redeemed?", a: "No — once a code is redeemed, it's tied to that account and can't be used again by anyone else." },
          { q: "Does my code work on both the app and the website?", a: "Yes — your account is shared across both, so a code redeemed on one is reflected immediately on the other." },
          { q: "Can a gift code also connect to a VIP perk?", a: "Some campaigns pair gift codes with VIP-related promotions, but Gift Code and VIP Club remain separate systems with their own mechanics." },
          { q: "Does the code field care about uppercase or lowercase?", a: "No — input is normalized automatically, so casing won't cause a valid code to fail." },
        ],
      },
      cta: {
        title: "Have a Code Ready to Redeem?",
        text: "Enter it above, or check Invite Code if you're looking to share your own referral code instead.",
        primary: { label: "View Invite Code", href: "/invite-code/" },
        secondary: { label: "View Rewards", href: "/rewards/" },
      },
    });
  },
};
