"use strict";
const { renderStandardPage } = require("../../components/pageBuilder");

module.exports = {
  slug: "/gift-code/",
  title: "55 Club Gift Code — Redemption Page Template",
  metaDescription:
    "The 55 Club Gift Code page template: a simple redemption-flow layout, code-format guidance and a plain explanation of expiry handling.",
  build() {
    return renderStandardPage({
      slug: "/gift-code/",
      breadcrumb: [{ label: "Home", href: "/" }, { label: "Gift Code" }],
      hero: {
        eyebrow: "Redemption",
        h1: "55 Club Gift Code",
        lead: "A single-field redemption layout template, with clear code-format guidance, specific error states and a plain explanation of what happens when a code is invalid, already used or expired.",
        primary: { label: "Register", href: "/register/" },
        secondary: { label: "See Invite Code", href: "/invite-code/" },
      },
      intro: [
        "Gift codes are a simple mechanic that real platforms frequently make more confusing than necessary — unclear formatting rules, vague error messages, and no explanation of where codes even come from in the first place. This template's redemption page addresses all three directly: a single input field with visible format guidance (length, character types), specific error states, and a short explanation of the channels codes are typically distributed through.",
        "The redemption flow itself is intentionally minimal — one field, one button, one clear success or error state. There's no multi-step wizard here, because a gift code redemption genuinely doesn't need one; adding steps to a simple action just increases the chance of abandonment partway through.",
        "Error handling gets specific treatment, distinguishing between a few common failure modes: an invalid format, a code that's already been used, and a code that's expired. Each produces a different message, because \"invalid code\" as a catch-all response leaves users guessing at what actually went wrong and whether it's worth trying again.",
        "This page sits alongside Invite Code as a related but distinct redemption mechanic — gift codes are typically distributed by the platform itself, while invite codes are typically generated by users for referral purposes. The distinction is worth stating plainly rather than letting the two blur together.",
      ],
      features: {
        eyebrow: "Gift Code Page Features",
        title: "What This Template Demonstrates",
        text: "Four patterns for a clean, low-friction redemption flow that gets out of the user's way.",
        cols: 4,
        items: [
          { icon: "ticket", title: "Single-Field Redemption", text: "One input, one action — no unnecessary steps for a simple task." },
          { icon: "check", title: "Format Guidance", text: "Visible hints on code length and character types before submission." },
          { icon: "shield", title: "Specific Error States", text: "Distinct messages for invalid, used and expired codes." },
          { icon: "gift", title: "Distribution Transparency", text: "A plain note on where codes typically come from." },
        ],
      },
      infoSections: [
        {
          eyebrow: "Redemption Flow",
          title: "One Field, Clear Feedback",
          paragraphs: [
            "This template's redemption form is deliberately narrow in scope: a text field with placeholder text showing the expected format, a submit button, and an inline result message that appears without a full page reload.",
            "Keeping the interaction on a single screen, with no navigation away and back, respects the fact that this is meant to be a quick, satisfying action — not a multi-step process.",
          ],
          sideList: {
            title: "Redemption Error States",
            items: [
              "Invalid format — code doesn't match expected pattern",
              "Already used — code was redeemed previously",
              "Expired — code's validity window has passed",
              "Not found — code doesn't exist in the system",
            ],
          },
        },
        {
          eyebrow: "Gift Code vs. Invite Code",
          title: "Two Related but Different Mechanics",
          reverse: true,
          paragraphs: [
            "Gift codes are typically issued by the platform — through promotions, events or customer support — while invite codes are typically generated by individual users to share with others as part of a referral system. This template keeps that distinction explicit rather than treating both as interchangeable.",
            "Both pages link to each other for anyone who arrived expecting the other mechanic, which is a common enough mix-up given how similar the two terms sound.",
          ],
          asideTitle: "Where Codes Typically Come From",
          asideText: "This template names typical distribution channels — promotional emails, event participation, social media announcements — as an example pattern, not a live list of current channels.",
        },
      ],
      extraSection: {
        eyebrow: "Security Considerations",
        title: "Why Redemption Forms Need Rate Limiting",
        paragraphs: [
          "A redemption field is a natural target for automated guessing if codes follow a predictable pattern, which is why any real implementation of this template should pair the frontend with server-side rate limiting and code entropy sufficient to resist brute-force attempts. This page can only communicate the interface pattern — the actual security has to live on the backend.",
          "The template's copy reflects this awareness in a small way: the format guidance shown to users describes length and character variety without revealing the actual generation algorithm, keeping the interface helpful without leaking implementation detail that could make guessing easier.",
          "The redemption endpoint is also a natural place for a lightweight CAPTCHA or similar friction step in a real system, triggered only after a small number of failed attempts rather than on every submission — enough to slow down automated guessing without punishing a legitimate user who simply mistyped a character.",
        ],
      },
      relatedLinks: {
        title: "Related Pages",
        links: [
          { label: "Invite Code", href: "/invite-code/" },
          { label: "Promotions", href: "/promotions/" },
          { label: "Bonus", href: "/bonus/" },
          { label: "Rewards", href: "/rewards/" },
          { label: "Customer Support", href: "/customer-support/" },
        ],
      },
      faq: {
        items: [
          { q: "How do I redeem a gift code?", a: "Enter it into the single redemption field and submit — this template's flow is intentionally a one-step process with immediate inline feedback." },
          { q: "What if my code doesn't work?", a: "The template distinguishes between four specific error states — invalid format, already used, expired, or not found — rather than one generic failure message." },
          { q: "Where do gift codes come from?", a: "Typically platform-issued through promotions, events or support channels, as opposed to invite codes, which are usually user-generated." },
          { q: "How is Gift Code different from Invite Code?", a: "Gift codes are issued by the platform; invite codes are generated by individual users for referral purposes. The two pages explain this distinction directly." },
          { q: "Is this redemption flow connected to a live system?", a: "No — it's a static content template demonstrating layout, copy and error-state patterns, not a functioning redemption backend." },
          { q: "Why does the page mention rate limiting?", a: "Because a real redemption endpoint needs backend protection against automated guessing — this page can only show the frontend pattern, not implement that security itself." },
          { q: "Can a code be used more than once?", a: "In this template's error-state pattern, a previously used code returns a distinct \"already used\" message rather than being silently accepted again." },
          { q: "Does repeated failed redemption trigger any protection?", a: "This template notes that a real system would likely add a lightweight friction step after several failed attempts, to slow automated guessing without punishing a simple typo." },
          { q: "Can a gift code also unlock a VIP-related perk?", a: "That's possible on a real platform depending on how programs are designed, though this template treats Gift Code and VIP Club as separate pages with their own distinct mechanics." },
          { q: "Does the redemption field accept lowercase and uppercase input?", a: "The template's format guidance pattern shows expected casing directly, and typically normalizes input automatically rather than rejecting a code purely for case mismatch." },
        ],
      },
      cta: {
        title: "Explore Related Reward Pages",
        text: "See how Invite Code and Rewards connect to this redemption mechanic, and how the three pages fit together.",
        primary: { label: "View Invite Code", href: "/invite-code/" },
        secondary: { label: "View Rewards", href: "/rewards/" },
      },
    });
  },
};
