"use strict";
const { renderStandardPage } = require("../../components/pageBuilder");

module.exports = {
  slug: "/invite-code/",
  title: "55 Club Invite Code — Refer Friends, Earn Bonuses",
  metaDescription:
    "Share your personal 55 Club invite code or link. When a friend registers with it and starts playing, you earn a referral bonus — refer more to unlock higher tiers.",
  build() {
    return renderStandardPage({
      slug: "/invite-code/",
      breadcrumb: [{ label: "Home", href: "/" }, { label: "Invite Code" }],
      hero: {
        eyebrow: "Referral Program",
        h1: "55 Club Invite Code",
        lead: "Your personal invite code and share link live on this page. Send it to a friend — when they register with it and start playing, you earn a referral bonus, and referring more friends unlocks higher referral tiers.",
        primary: { label: "Register", href: "/register/" },
        secondary: { label: "See Gift Code", href: "/gift-code/" },
      },
      intro: [
        "Every account gets one personal invite code, generated automatically the moment you register and displayed right here alongside a one-click copy button and a ready-to-share link. There's nothing to set up — the code is already waiting for you.",
        "Share it however's easiest — drop the link in a group chat, post it, or just send the code directly. When someone signs up using your code and starts playing, the referral is tracked automatically and a referral bonus is credited to your account.",
        "Refer enough friends and you move up through referral tiers, with each tier unlocking a better rate or bonus structure than the last. The more active referrals you bring in, the more this page pays out over time — it's designed to reward consistent sharing, not just a single referral.",
        "This page connects with Gift Code, which is the platform's own promo-code system rather than a referral one — worth knowing the difference if you were expecting one and landed on the other.",
      ],
      features: {
        eyebrow: "Invite Code Page Features",
        title: "How Referrals Work",
        text: "Four things that make sharing your code worthwhile.",
        cols: 4,
        items: [
          { icon: "spark", title: "One-Click Copy", text: "Your code and a ready-made share link, copied in a single tap." },
          { icon: "coin", title: "Referral Bonus", text: "Earn a bonus automatically when a referred friend registers and plays." },
          { icon: "crown", title: "Referral Tiers", text: "Refer more friends to unlock higher referral tiers and better rewards." },
          { icon: "check", title: "Activity Tracking", text: "See your referral count and earned bonuses right on this page." },
        ],
      },
      infoSections: [
        {
          eyebrow: "How Codes Are Generated",
          title: "One Code Per Account, Ready to Share",
          paragraphs: [
            "Your invite code is assigned automatically when you register and shown prominently on this page, along with a pre-formatted link and a one-click copy button — no manual formatting required on your end.",
            "Keeping the code easy to find and copy matters because most referral sharing happens in the moment — a friend asks where you play, and you want to send the link right then, not dig through account settings to find it.",
          ],
          sideList: {
            title: "What This Page Shows",
            items: [
              "Your personal invite code",
              "A ready-to-share link",
              "A one-click copy button",
              "Your referral count and earned bonuses",
            ],
          },
        },
        {
          eyebrow: "How Tracking Works",
          title: "From Sign-Up to Bonus Credit",
          reverse: true,
          paragraphs: [
            "When a friend registers using your code, that connection is recorded immediately — no extra step needed on their end beyond entering the code at sign-up. Once they start playing, your referral bonus is credited to your account automatically.",
            "You'll see the referral reflected on this page: your total referral count updates, and any bonus earned from that referral shows up alongside it, so you always know exactly what your sharing has earned you.",
          ],
          asideTitle: "Referring More Unlocks More",
          asideText: "Referral tiers reward volume — the more friends you successfully refer, the higher the tier you reach, and each tier up improves the referral bonus rate.",
        },
      ],
      extraSection: {
        eyebrow: "Invite Code vs. Gift Code",
        title: "Two Similar-Sounding, Different Mechanics",
        paragraphs: [
          "Invite Code and Gift Code get mixed up often because the names sound alike, so it's worth being direct about the difference. Your invite code is generated by you and shared with others — it's how you earn a referral bonus. A gift code is issued by 55 Club and redeemed by you — it's how you claim a promo credit someone else sent you, or one we released publicly.",
          "If you're here to share your own code and start earning referral bonuses, you're in the right place. If you were handed a code by a friend or found one through a promotion and you're trying to redeem it, head to Gift Code instead.",
          "Both systems can be active on the same account at once — using a gift code you received doesn't affect your invite code, and sharing your invite code doesn't use up any gift codes. They run independently.",
        ],
      },
      relatedLinks: {
        title: "Related Pages",
        links: [
          { label: "Gift Code", href: "/gift-code/" },
          { label: "Rewards", href: "/rewards/" },
          { label: "VIP Club", href: "/vip-club/" },
          { label: "Register", href: "/register/" },
          { label: "Promotions", href: "/promotions/" },
        ],
      },
      faq: {
        items: [
          { q: "How do I get my invite code?", a: "It's generated automatically when you register and displayed on this page with a one-click copy button — nothing extra to set up." },
          { q: "How does referral tracking work?", a: "When someone registers using your code, the connection is recorded immediately. Once they start playing, your referral bonus is credited automatically." },
          { q: "How is Invite Code different from Gift Code?", a: "Your invite code is generated by you and shared with friends to earn referral bonuses; a gift code is issued by 55 Club and redeemed on the Gift Code page." },
          { q: "Can I share my invite code on social media?", a: "Yes — the pre-formatted share link on this page is built for exactly that, alongside the raw code if you'd rather send that directly." },
          { q: "Is my referral activity visible to me?", a: "Yes — your referral count and the bonuses you've earned from them are both shown on this page." },
          { q: "What do I earn when someone uses my code?", a: "A referral bonus credited to your account once your referred friend registers and starts playing." },
          { q: "Do referral tiers unlock better rewards?", a: "Yes — refer more friends and you move up through referral tiers, each one improving your referral bonus rate." },
          { q: "Why does this page read differently from the Gift Code page?", a: "Invite Code is about sharing — it's built around your code and your referral activity. Gift Code is about redeeming — it's built around entering a code you received." },
          { q: "Can I have more than one invite code?", a: "Each account has a single persistent invite code, so you'll always be sharing the same one." },
        ],
      },
      cta: {
        title: "Start Sharing Your Code",
        text: "Copy your invite link above and start earning referral bonuses for every friend who joins and plays.",
        primary: { label: "View Rewards", href: "/rewards/" },
        secondary: { label: "View VIP Club", href: "/vip-club/" },
      },
    });
  },
};
